name: Build PBIX Extractor

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed `
          --add-data "bin/pbi-tools.exe;bin" `
          --add-binary "bin/pbi-tools.exe;bin" `
          --hidden-import tkinter `
          --hidden-import tkinter.ttk `
          --hidden-import tkinter.filedialog `
          --hidden-import tkinter.messagebox `
          --name "pbix-extractor" `
          --icon "assets/icon.ico" `
          main.py
        
    - name: Create distribution package
      run: |
        Copy-Item README.md dist/
        Copy-Item LICENSE.md dist/
        Compress-Archive -Path dist/pbix-extractor.exe, dist/README.md, dist/LICENSE.md -DestinationPath dist/pbix-extractor.zip
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: pbix-extractor-windows
        path: dist/pbix-extractor.zip