name: Build PBIX Extractor

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --noconsole `
          --add-data "bin/win/*;bin/win/" `
          --add-data "bin/core/*;bin/core/" `
          --add-data "bin/linux/*;bin/linux/" `
          --hidden-import tkinter `
          --hidden-import tkinter.ttk `
          --hidden-import tkinter.filedialog `
          --hidden-import tkinter.messagebox `
          --name "pbix-extractor" `
          --icon "assets/icon.ico" `
          main.py
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: pbix-extractor-windows
        path: dist/pbix-extractor.zip